export {default as Home} from "./Home"
export {default as FAQ} from "./Faq"
export {default as Talks} from "./Talks"
export {default as Agenda} from "./Agenda"
export {default as Sponsors} from "./Sponsors"
export {default as Workshops} from "./Workshops"