export {default as Home} from "./Home"
export {default as Faq} from "./Faq"
export {default as Conferences} from "./Conferences"
export {default as Agenda} from "./Agenda"
export {default as Sponsors} from "./Sponsors"
export {default as Workshops} from "./Workshops"